local:
  hosts:
    localhost: 
      vars:
        ansible_connection: local
  vars:
    grafana_user: admin
    grafana_password: password
    monitored_hosts: 
      - 192.168.196.208
      - 192.168.196.64

    snmp_modules:
      - if_mib
      - ucd_snmp_mib

    blackbox_modules:
      - icmp
