global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "snmp exporter"
    static_configs:
      - targets: ['192.168.196.208', '192.168.196.64']
        labels:
          job: "snmp exporter"
    metrics_path: /snmp
    params:
      module: ['if_mib', 'ucd_snmp_mib', 'host_resources_mib']
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "snmp_exporter:9116"
  - job_name: "blackbox exporter"
    static_configs:
      - targets: ['192.168.196.208', '192.168.196.64']
        labels:
          job: "blackbox exporter"
    metrics_path: /probe
    params:
      module: ['icmp']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"
