---
- name: Generate configs
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: group_vars/custom_vars.yml
  tasks:
    - name: Create docker compose file
      template:
        src: templates/docker-compose.yml.j2
        dest: ../../docker-compose.yml

    - name: Create prometheus config
      template:
        src: templates/prometheus.yml.j2
        dest: ../../prometheus/prometheus.yml
    
    - name: Create snmp_exporter config
      template:
        src: templates/generator.yml.j2
        dest: ../../snmp_exporter/generator/generator.yml

    - name: Generate snmp.yml
      command: ./generator generate -o ../snmp.yml
      args:
        chdir: ../../snmp_exporter/generator


